### ISSUE TITLE
add support for Vault connectivity in consul template config.json

### ISSUE THREAD

**Issue by sjoeboo** [claranet/puppet-consul_template#24]
per Consul-tempalte docs, something like like

```
vault {
  address = "https://vault.service.consul:8200"
  token = "abcd1234" // May also be specified via the envvar VAULT_TOKEN
  ssl {
    enabled = true
    verify = true
    cert = "/path/to/client/cert.pem"
    ca_cert = "/path/to/ca/cert.pem"
  }
}
```

I'd be happy with even just passing this in a hash directly, ie:

```

---
consul_template::vault_config_hash:
  address: "https://vault.service.consul:8200"
  token: "abcd1234"
  ssl:
    enabled: true
    verify: true
    cert: "/path/to/client/cert.pem"
    ca_cert: "/path/to/ca/cert.pem"
```
